### ISSUE TITLE
case statement doesn't work in where clause

### ISSUE THREAD

**Issue by ilkergurelli** [panates/sqb#12]

**Comment by erayhanoglu** [comment]
Can you provide an example?

**Comment by ilkergurelli** [comment]
select * from accounts a
where a.process_date > case when a.laboratory_fl =140 then a.study_date else a.point_date end

**Comment by erayhanoglu** [comment]
I mean example js code. not the plain sql

**Comment by ilkergurelli** [comment]
select(
        'b.ID as book_id', 'b.name book_name', 'c.name category_name',
        sqb.case().when('id','1').then('Order 1').when('id','2').then('Order 2')
    ).from('BOOKS b')
        .where(
            ['b.id', '>=', 1],
            [sqb.case().when('id','2').then('abc').when('id','4').then('def'),'=','def']
        )
