### ISSUE TITLE
where clause dosn't accept sql statement

### ISSUE THREAD

**Issue by ecemerimguner** [panates/sqb#21]
select('B.WRITER_ID', 'B.NAME').from('BOOK B')
        .where('B.WRITER_ID',select('W.WRITER_ID').from('WRITER W').where(['W.NAME','=','AZRA']))

sql output:
select B.WRITER_ID, B.NAME from BOOK B where B.WRITER_ID = '[object Object]'

**Comment by erayhanoglu** [comment]
Will be fixed in next commit.
